<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.2" name="tileset" tilewidth="16" tileheight="16" tilecount="575" columns="25">
 <image source="./tileset.png" width="400" height="368"/>
 <tile id="26" type="ground"/>
 <tile id="28" type="ground"/>
 <tile id="30" type="ground"/>
 <tile id="32" type="ground"/>
 <tile id="34" type="top-blocking"/>
 <tile id="35" type="top-blocking"/>
 <tile id="36" type="ground"/>
 <tile id="38" type="ground"/>
 <tile id="39" type="ground"/>
 <tile id="41" type="ground"/>
 <tile id="42" type="ground"/>
 <tile id="44" type="ground"/>
 <tile id="45" type="ground"/>
 <tile id="47" type="ground"/>
 <tile id="48" type="ground"/>
 <tile id="63" type="ground"/>
 <tile id="64" type="ground"/>
 <tile id="66" type="ground"/>
 <tile id="67" type="ground"/>
 <tile id="69" type="ground"/>
 <tile id="70" type="ground"/>
 <tile id="72" type="ground"/>
 <tile id="73" type="ground"/>
 <tile id="76" type="ground"/>
 <tile id="78" type="ground"/>
 <tile id="80" type="ground"/>
 <tile id="82" type="ground"/>
 <tile id="83" type="top-blocking"/>
 <tile id="85" type="top-blocking"/>
 <tile id="86" type="ground"/>
 <tile id="114" type="ground"/>
 <tile id="116" type="ground"/>
 <tile id="120" type="ground"/>
 <tile id="122" type="ground"/>
 <tile id="126" type="ground"/>
 <tile id="128" type="ground"/>
 <tile id="130" type="ground"/>
 <tile id="132" type="ground"/>
 <tile id="133" type="top-blocking"/>
 <tile id="134" type="top-blocking"/>
 <tile id="139" type="ground"/>
 <tile id="141" type="ground"/>
 <tile id="145" type="ground"/>
 <tile id="147" type="ground"/>
 <tile id="180" type="ground"/>
 <tile id="182" type="ground"/>
 <tile id="190" type="ground"/>
 <tile id="192" type="ground"/>
 <tile id="194" type="ground"/>
 <tile id="240" type="ground"/>
 <tile id="242" type="ground"/>
 <tile id="244" type="ground"/>
 <tile id="251" type="ground"/>
 <tile id="252" type="ground"/>
 <tile id="254" type="ground"/>
 <tile id="255" type="ground"/>
 <tile id="257" type="stairs"/>
 <tile id="277" type="ground"/>
 <tile id="279" type="ground"/>
 <tile id="290" type="ground"/>
 <tile id="292" type="ground"/>
 <tile id="294" type="ground"/>
 <tile id="332" type="ground"/>
 <tile id="334" type="ground"/>
 <tile id="336" type="ground"/>
 <tile id="338" type="ground"/>
 <tile id="361" type="ground"/>
 <tile id="365" type="ground"/>
 <tile id="367" type="ground"/>
 <tile id="369" type="ground"/>
 <tile id="376" type="ground"/>
 <tile id="377" type="ground"/>
 <tile id="379" type="ground"/>
 <tile id="380" type="ground"/>
 <tile id="401" type="ground"/>
 <tile id="402" type="ground"/>
 <tile id="404" type="ground"/>
 <tile id="426" type="ground"/>
 <tile id="427" type="ground"/>
 <tile id="429" type="ground"/>
 <tile id="430" type="ground"/>
 <tile id="451" type="ground"/>
 <tile id="452" type="ground"/>
 <tile id="454" type="ground"/>
 <tile id="455" type="ground"/>
 <tile id="467" type="ground"/>
 <tile id="501" type="block"/>
 <tile id="503" type="block"/>
 <tile id="504" type="block"/>
 <tile id="528" type="block"/>
 <tile id="529" type="block"/>
</tileset>
